### ISSUE TITLE
Tracking Issue for Workspace Lints

### ISSUE THREAD

**Issue by hinto-janai** [Cuprate/cuprate#207]
### About tracking issues
Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however not meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter.

### What
This is a tracking issue for initial integration of lints in our workspace's `Cargo.toml` and codebase.

### Steps

- [x] Initial proposal: https://github.com/Cuprate/cuprate/issues/131
- [x] Add lints to workspace `Cargo.toml`: https://github.com/Cuprate/cuprate/issues/133
- [x] Opt crates in
    - [x] cuprate-fast-sync: https://github.com/Cuprate/cuprate/pull/295
    - [x] cuprate-consensus-context: https://github.com/Cuprate/cuprate/pull/321
    - [x] cuprate-consensus-rules: https://github.com/Cuprate/cuprate/pull/295
    - [x] cuprate-constants: https://github.com/Cuprate/cuprate/pull/280
    - [x] cuprate-consensus: https://github.com/Cuprate/cuprate/pull/295
    - [x] cuprate-cryptonight: https://github.com/Cuprate/cuprate/pull/271
    - [x] cuprate-helper: https://github.com/Cuprate/cuprate/pull/263
    - [x] cuprate-epee-encoding: https://github.com/Cuprate/cuprate/pull/294
    - [x] cuprate-fixed-bytes: https://github.com/Cuprate/cuprate/pull/293
    - [x] cuprate-levin: https://github.com/Cuprate/cuprate/pull/292
    - [x] cuprate-wire: https://github.com/Cuprate/cuprate/pull/291
    - [x] cuprate-p2p: https://github.com/Cuprate/cuprate/pull/289
    - [x] cuprate-p2p-core: https://github.com/Cuprate/cuprate/pull/288
    - [x] cuprate-dandelion-tower: https://github.com/Cuprate/cuprate/pull/287
    - [x] cuprate-address-book: https://github.com/Cuprate/cuprate/pull/285
    - [x] cuprate-blockchain: https://github.com/Cuprate/cuprate/pull/263
    - [x] cuprate-database: https://github.com/Cuprate/cuprate/pull/263
    - [x] cuprate-txpool: https://github.com/Cuprate/cuprate/pull/263
    - [x] cuprate-pruning: https://github.com/Cuprate/cuprate/pull/284
    - [x] cuprate-test-utils: https://github.com/Cuprate/cuprate/pull/283
    - [x] cuprate-types: https://github.com/Cuprate/cuprate/pull/263
    - [x] cuprate-json-rpc: https://github.com/Cuprate/cuprate/pull/263
    - [x] cuprate-rpc-types: https://github.com/Cuprate/cuprate/pull/263
    - [x] cuprate-rpc-interface: https://github.com/Cuprate/cuprate/pull/263
