### ISSUE TITLE
Tracking Issue for Benchmarks

### ISSUE THREAD

**Issue by hinto-janai** [Cuprate/cuprate#208]
### About tracking issues
Tracking issues are used to record the overall progress of implementation. They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions. A tracking issue is however not meant for large scale discussion, questions, or bug reports about a feature. Instead, open a dedicated issue for the specific matter.

### What
This is a tracking issue for integrating benchmarking for Cuprate as described in #193.

### Steps

- [x] Initial proposal: https://github.com/Cuprate/cuprate/issues/193
- [ ] `benches/` initial setup: https://github.com/Cuprate/cuprate/pull/196 
- [ ] Criterion benchmarks
    - [ ] cuprate-fast-sync
    - [ ] cuprate-consensus-rules
    - [ ] cuprate-cryptonight
    - [ ] cuprate-helper
    - [ ] cuprate-epee-encoding
    - [ ] cuprate-fixed-bytes
    - [ ] cuprate-levin
    - [ ] cuprate-wire
    - [ ] cuprate-p2p
    - [ ] cuprate-p2p-core
    - [ ] cuprate-dandelion-tower
    - [ ] cuprate-address-book
    - [ ] cuprate-blockchain
    - [ ] cuprate-database
    - [ ] cuprate-txpool
    - [ ] cuprate-pruning
    - [ ] cuprate-test-utils
    - [ ] cuprate-types
    - [ ] cuprate-json-rpc
    - [ ] cuprate-rpc-types
    - [ ] cuprate-rpc-interface
- [ ] Harness benchmarks
    - [ ] TBD
