### ISSUE TITLE
Tracking Issue for RPC handlers

### ISSUE THREAD

**Issue by hinto-janai** [Cuprate/cuprate#244]
### About tracking issues
Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however not meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter.

### What
This is a tracking issue for Cuprate's initial RPC handler implementation. The RPC handlers build upon the previous crates created in https://github.com/Cuprate/cuprate/issues/183. They implement the function bodies responsible for mapping requests to responses.

### Steps

- [ ] Handlers
    - [ ] Misc fixes
        -  [ ] TODO
    - [ ] `/json_rpc`
    - [ ] Other JSON 
    - [ ] Binary
- [ ] Binary string handling
    - [ ] `monero-core` discussion
    - [ ]  Cuprate implementation
- [ ] Doc-tests
    - [ ] Binary request/response data
    - [ ] Binary types
    - [ ] Mixed types
- [ ] Documentation
    - [ ] Architecture book 
    - [ ] `cuprate-rpc-handler` crate docs

### Related
