### ISSUE TITLE
Chain manager

### ISSUE THREAD

**Issue by Boog900** [Cuprate/cuprate#247]
### About tracking issues
Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however not meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter.

### What

The chain manager, which is the task in `cuprated` that handles incoming blocks from peers or the syncer.

### Steps

- [] Chain syncer
- [ ] Handle new blocks 
    - [ ] From the peer channel
    - [ ] From the syncer channel
- [ ] Handle chain re-orgs

### Related

I started the syncer here: https://github.com/Cuprate/cuprate/pull/142
