### ISSUE TITLE
P2P request handler 

### ISSUE THREAD

**Issue by Boog900** [Cuprate/cuprate#248]
### About tracking issues
Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however not meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter.

### What

The p2p protocol request handler service.

### Steps

- [ ] Handle incoming tx-pool txs
- [ ] Handle new fluffy blocks
- [ ] Handle other requests
