### ISSUE TITLE
Tracking Issue for `/tests`

### ISSUE THREAD

**Issue by hinto-janai** [Cuprate/cuprate#351]
### About tracking issues
Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however not meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter.

### What
This is a tracking issue for the initial `/tests` directory and the tests needed within it before a public stable release.

### Steps
- [ ] Initial PR + documentation
- [ ] RPC compatibility with  `monerod`
- [ ] DB migration (all backends)
